<a href="https://colab.research.google.com/github/adnaaan10/Handling_Of_Categorical_Values/blob/main/Handling_of_categorical_variableipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/customer.csv')
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

# **ORDINAL ENCODING FOR INDIPENDENT VARIABLE**

In [3]:
from sklearn.preprocessing import OrdinalEncoder

In [4]:
review_order=['Poor','Average','Good']
education_order=['School','UG','PG']
encoder=OrdinalEncoder(categories=[review_order,education_order])

In [5]:
df[['review','education']]=encoder.fit_transform(df[['review','education']])

In [6]:
df

    age  gender  review  education purchased
0    30  Female     1.0        0.0        No
1    68  Female     0.0        1.0        No
2    70  Female     2.0        2.0        No
3    72  Female     2.0        2.0        No
4    16  Female     1.0        1.0        No
5    31  Female     1.0        0.0       Yes
6    18    Male     2.0        0.0        No
7    60  Female     0.0        0.0       Yes
8    65  Female     1.0        1.0        No
9    74    Male     2.0        1.0       Yes
10   98  Female     2.0        1.0       Yes
11   74    Male     2.0        1.0       Yes
12   51    Male     0.0        0.0        No
13   57  Female     1.0        0.0        No
14   15    Male     0.0        2.0       Yes
15   75    Male     0.0        1.0        No
16   59    Male     0.0        1.0       Yes
17   22  Female     0.0        1.0       Yes
18   19    Male     2.0        0.0        No
19   97    Male     0.0        2.0       Yes
20   57  Female     1.0        0.0       Yes
21   32    Male     1.0        2.0        No
22   18  Female     0.0        2.0       Yes
23   96  Female     2.0        0.0        No
24   16  Female     1.0        2.0       Yes
25   57  Female     2.0        0.0        No
26   53  Female     0.0        2.0        No
27   69  Female     0.0        2.0        No
28   48    Male     0.0        0.0        No
29   83  Female     1.0        1.0       Yes
30   73    Male     1.0        1.0        No
31   22  Female     0.0        0.0       Yes
32   92    Male     1.0        1.0       Yes
33   89  Female     2.0        2.0       Yes
34   86    Male     1.0        0.0        No
35   74    Male     0.0        0.0       Yes
36   34  Female     2.0        1.0       Yes
37   94    Male     1.0        2.0       Yes
38   45  Female     2.0        0.0        No
39   76    Male     0.0        2.0        No
40   39    Male     2.0        0.0        No
41   23    Male     2.0        2.0       Yes
42   30  Female     2.0        2.0       Yes
43   27    Male     0.0        2.0        No
44   77  Female     1.0        1.0        No
45   61    Male     0.0        2.0       Yes
46   64  Female     0.0        2.0        No
47   38  Female     2.0        2.0       Yes
48   39  Female     2.0        1.0       Yes
49   25  Female     2.0        1.0        No

# **LABEL ENCODING FOR TARGET VARIABLE**

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
df['purchased']=LabelEncoder().fit_transform(df['purchased'])

In [9]:
df

    age  gender  review  education  purchased
0    30  Female     1.0        0.0          0
1    68  Female     0.0        1.0          0
2    70  Female     2.0        2.0          0
3    72  Female     2.0        2.0          0
4    16  Female     1.0        1.0          0
5    31  Female     1.0        0.0          1
6    18    Male     2.0        0.0          0
7    60  Female     0.0        0.0          1
8    65  Female     1.0        1.0          0
9    74    Male     2.0        1.0          1
10   98  Female     2.0        1.0          1
11   74    Male     2.0        1.0          1
12   51    Male     0.0        0.0          0
13   57  Female     1.0        0.0          0
14   15    Male     0.0        2.0          1
15   75    Male     0.0        1.0          0
16   59    Male     0.0        1.0          1
17   22  Female     0.0        1.0          1
18   19    Male     2.0        0.0          0
19   97    Male     0.0        2.0          1
20   57  Female     1.0        0.0          1
21   32    Male     1.0        2.0          0
22   18  Female     0.0        2.0          1
23   96  Female     2.0        0.0          0
24   16  Female     1.0        2.0          1
25   57  Female     2.0        0.0          0
26   53  Female     0.0        2.0          0
27   69  Female     0.0        2.0          0
28   48    Male     0.0        0.0          0
29   83  Female     1.0        1.0          1
30   73    Male     1.0        1.0          0
31   22  Female     0.0        0.0          1
32   92    Male     1.0        1.0          1
33   89  Female     2.0        2.0          1
34   86    Male     1.0        0.0          0
35   74    Male     0.0        0.0          1
36   34  Female     2.0        1.0          1
37   94    Male     1.0        2.0          1
38   45  Female     2.0        0.0          0
39   76    Male     0.0        2.0          0
40   39    Male     2.0        0.0          0
41   23    Male     2.0        2.0          1
42   30  Female     2.0        2.0          1
43   27    Male     0.0        2.0          0
44   77  Female     1.0        1.0          0
45   61    Male     0.0        2.0          1
46   64  Female     0.0        2.0          0
47   38  Female     2.0        2.0          1
48   39  Female     2.0        1.0          1
49   25  Female     2.0        1.0          0

# **ONE HOT ENCODING USING PANDAS**

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv('/content/cars.csv')

In [12]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [13]:
df1=pd.get_dummies(df[['fuel','owner']]).astype('int')
df1

,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0,1,0,0,1,0,0,0,0
1,0,1,0,0,0,0,1,0,0
2,0,0,0,1,0,0,0,0,1
3,0,1,0,0,1,0,0,0,0
4,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
8123,0,0,0,1,1,0,0,0,0
8124,0,1,0,0,0,1,0,0,0
8125,0,1,0,0,1,0,0,0,0
8126,0,1,0,0,1,0,0,0,0
8127,0,1,0,0,1,0,0,0,0

In [14]:
df2=df[['brand','km_driven','selling_price']]
df2

        brand  km_driven  selling_price
0      Maruti     145500         450000
1       Skoda     120000         370000
2       Honda     140000         158000
3     Hyundai     127000         225000
4      Maruti     120000         130000
...       ...        ...            ...
8123  Hyundai     110000         320000
8124  Hyundai     119000         135000
8125   Maruti     120000         382000
8126     Tata      25000         290000
8127     Tata      25000         290000

[8128 rows x 3 columns]

In [15]:
df3=pd.concat([df2,df1],axis=1)
df3

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [20]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
X_test_new=ohe.fit_transform(X_test[['fuel','owner']])

In [21]:
X_train_new.toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

**Another method**

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype='int64')

In [23]:
X_train_new_1=ohe.fit_transform(X_train[['fuel','owner']])
X_test_new_1=ohe.fit_transform(X_test[['fuel','owner']])

In [24]:
X_train_new_1

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [25]:
import numpy as np
a=np.hstack((X_train[['brand','km_driven']].values,X_train_new_1))

In [26]:
num_ohe_features = X_train_new.shape[1]  # Get the number of features from X_train_new
pd.DataFrame(a, columns=['brand', 'km_driven'] + ohe.get_feature_names_out().tolist()[:num_ohe_features])

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Hyundai,35000,1,0,0,0,0,0,0
1,Jeep,60000,1,0,0,0,0,0,0
2,Hyundai,25000,0,0,1,0,0,0,0
3,Mahindra,130000,1,0,0,0,1,0,0
4,Hyundai,155000,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
6497,Ford,35000,1,0,0,0,0,0,0
6498,Maruti,120000,0,0,1,0,0,0,0
6499,Tata,15000,0,0,1,0,0,0,0
6500,Maruti,32500,1,0,0,0,1,0,0
6501,Isuzu,121000,1,0,0,0,0,0,0